"use client";
/* eslint-disable @next/next/no-html-link-for-pages */
import { useEffect, useMemo, useState } from "react";
import "./club.css";

type Post={id:number;kind:string;title:string;body:string;userEmail?:string;createdAt?:string};
const kinds=[{id:"all",label:"ทั้งหมด",icon:"✦"},{id:"book",label:"หนังสือ",icon:"▤"},{id:"podcast",label:"พอดแคสต์",icon:"◉"},{id:"music",label:"เพลง",icon:"♫"},{id:"movie",label:"หนัง",icon:"▶"},{id:"cafe",label:"คาเฟ่",icon:"☕"}];
const samples:Post[]=[
  {id:-1,kind:"book",title:"วันที่เริ่มอะไรไม่ไหว ลองเปิด Atomic Habits แค่หนึ่งบท",body:"ไม่ได้อ่านเพื่อเปลี่ยนชีวิตในคืนเดียว แค่อยากให้วันนี้มีสิ่งเล็ก ๆ ที่ทำสำเร็จ การวางหนังสือไว้ข้างแก้วกาแฟช่วยให้เราเริ่มด้วยสองหน้าได้จริง",userEmail:"Mild · Cup of Tiny Starts",createdAt:"เมื่อ 12 นาทีที่แล้ว"},
  {id:-2,kind:"cafe",title:"มุมริมหน้าต่างกับลาเต้ไม่หวาน คือพื้นที่พักที่พอดี",body:"ร้านไม่ต้องเงียบสนิท แค่มีโต๊ะที่ไม่เร่งเรา วันนี้พก The Comfort Book ไป อ่านสลับกับมองคนเดินผ่านแล้วรู้สึกว่าใจกลับมาอยู่กับตัวเอง",userEmail:"June · Cup of Calm",createdAt:"เมื่อ 34 นาทีที่แล้ว"},
  {id:-3,kind:"podcast",title:"พอดแคสต์ตอนนี้ทำให้คำว่า “พัก” ไม่รู้สึกผิด",body:"ฟังระหว่างเดินกลับบ้าน ความยาวยี่สิบนาทีพอดี ประโยคที่เก็บกลับมาคือ เราไม่จำเป็นต้องทำทุกช่วงเวลาให้เกิดประโยชน์",userEmail:"Tin · Cup of Enough",createdAt:"เมื่อ 1 ชั่วโมงที่แล้ว"},
];

export default function ClubPage(){
  const [posts,setPosts]=useState<Post[]>([]);const [title,setTitle]=useState("");const [body,setBody]=useState("");const [kind,setKind]=useState("book");const [filter,setFilter]=useState("all");const [expanded,setExpanded]=useState(false);const [liked,setLiked]=useState<Set<number>>(new Set());const [saved,setSaved]=useState<Set<number>>(new Set());
  const load=()=>fetch("/api/community").then(r=>r.json()).then(d=>setPosts(d.posts??[])).catch(()=>setPosts([]));
  useEffect(()=>{load()},[]);
  const publish=async()=>{let guestId=localStorage.getItem("cup-of-us-guest");if(!guestId){guestId=`guest-${crypto.randomUUID()}`;localStorage.setItem("cup-of-us-guest",guestId)}const response=await fetch("/api/community",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({guestId,kind,title,body})});if(response.ok){setTitle("");setBody("");setExpanded(false);load()}};
  const feed=useMemo(()=>{const source=posts.length?posts:samples;return filter==="all"?source:source.filter(post=>post.kind===filter)},[posts,filter]);
  const toggle=(setter:React.Dispatch<React.SetStateAction<Set<number>>>,id:number)=>setter(current=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next});
  return <main className="club-page"><nav className="catalog-nav"><a className="logo" href="/"><span>CUP</span><i>of</i><span>US</span></a></nav>
    <header className="club-feed-hero club-feed-simple"><div><p className="eyebrow">CUP CLUB</p><h1>เล่าต่อสิ่งดี ๆ<br/><em>ที่เพิ่งค้นพบ</em></h1><p>หนังสือ เพลง หนัง พอดแคสต์ และคาเฟ่ที่ช่วยให้วันธรรมดาดีขึ้น</p></div><a href="#compose" aria-label="เขียนโพสต์ใหม่"><span>＋</span><b>เขียนโพสต์<small>แบ่งปันสั้น ๆ ได้เลย</small></b></a></header>
    <div className="club-shell club-shell-simple"><section className="club-stream"><nav className="club-filter" aria-label="กรองโพสต์">{kinds.map(item=><button className={filter===item.id?"active":""} onClick={()=>setFilter(item.id)} type="button" key={item.id}><i>{item.icon}</i><span>{item.label}</span></button>)}</nav><form id="compose" className={`club-inline-compose${expanded?" is-expanded":""}`} onSubmit={event=>{event.preventDefault();publish()}}><div className="club-avatar">CU</div><div><label htmlFor="club-title">มีอะไรอยากบอกต่อ?</label><input id="club-title" value={title} onFocus={()=>setExpanded(true)} onChange={event=>setTitle(event.target.value)} required placeholder="พิมพ์ชื่อสิ่งที่คุณชอบ"/>{expanded&&<><textarea value={body} onChange={event=>setBody(event.target.value)} required placeholder="เล่าสั้น ๆ ว่ามันดีกับคุณอย่างไร"/><footer><div>{kinds.slice(1).map(item=><button className={kind===item.id?"active":""} onClick={()=>setKind(item.id)} type="button" key={item.id}><i>{item.icon}</i><span>{item.label}</span></button>)}</div><button className="club-publish" type="submit">โพสต์ →</button></footer></>}</div></form>
        <div className="club-stream-head"><div><p className="eyebrow">FRESHLY BREWED</p><h2>{kinds.find(item=>item.id===filter)?.label??"ทั้งหมด"}</h2></div><span>{feed.length} โพสต์</span></div>
        <div className="club-post-list">{feed.length?feed.map((post,index)=>{const meta=kinds.find(item=>item.id===post.kind)??kinds[1];return <article className={`club-post note-${index%3}`} key={post.id}><div className="club-post-avatar">{meta.icon}</div><div className="club-post-content"><header><div><b>{post.userEmail?.split("@")[0]??"สมาชิก Cup of Us"}</b><span>· {post.createdAt&&post.createdAt.includes("T")?"โพสต์ล่าสุด":post.createdAt??"เพิ่งแปะ"}</span></div><small>{meta.icon} {meta.label}</small></header><h3>{post.title}</h3><p>{post.body}</p><footer><button className={liked.has(post.id)?"active":""} onClick={()=>toggle(setLiked,post.id)} type="button" aria-label="ถูกใจโพสต์"><i>♡</i><span>{liked.has(post.id)?"ถูกใจแล้ว":"ถูกใจ"}</span></button><button type="button"><i>↳</i><span>ตอบกลับ</span></button><button type="button"><i>↗</i><span>ส่งต่อ</span></button><button className={saved.has(post.id)?"active save":"save"} onClick={()=>toggle(setSaved,post.id)} type="button"><i>▣</i><span>{saved.has(post.id)?"เก็บแล้ว":"เก็บโพสต์"}</span></button></footer></div></article>}):<div className="club-empty"><span>☕</span><h3>มุมนี้ยังว่างอยู่</h3><p>ลองแปะโพสต์แรกของรสนี้ให้คนถัดไปได้เจอ</p><button onClick={()=>document.getElementById("club-title")?.focus()} type="button">เริ่มเขียนโพสต์ →</button></div>}</div>
      </section></div>
  </main>;
}
