"use client";
/* eslint-disable @next/next/no-html-link-for-pages */
import { useEffect, useMemo, useState } from "react";
import "./club.css";

type Post={id:number;kind:string;title:string;body:string;userEmail?:string;createdAt?:string};
const kinds=[{id:"all",label:"ทั้งหมด",icon:"✦"},{id:"book",label:"หนังสือ",icon:"▤"},{id:"podcast",label:"พอดแคสต์",icon:"◉"},{id:"music",label:"เพลง",icon:"♫"},{id:"movie",label:"หนัง",icon:"▶"},{id:"cafe",label:"คาเฟ่",icon:"☕"}];
const samples:Post[]=[
  {id:-1,kind:"book",title:"วันที่เริ่มอะไรไม่ไหว ลองเปิด Atomic Habits แค่หนึ่งบท",body:"ไม่ได้อ่านเพื่อเปลี่ยนชีวิตในคืนเดียว แค่อยากให้วันนี้มีสิ่งเล็ก ๆ ที่ทำสำเร็จ การวางหนังสือไว้ข้างแก้วกาแฟช่วยให้เราเริ่มด้วยสองหน้าได้จริง",userEmail:"Mild · Cup of Tiny Starts",createdAt:"เมื่อ 12 นาทีที่แล้ว"},
  {id:-2,kind:"cafe",title:"มุมริมหน้าต่างกับลาเต้ไม่หวาน คือพื้นที่พักที่พอดี",body:"ร้านไม่ต้องเงียบสนิท แค่มีโต๊ะที่ไม่เร่งเรา วันนี้พก The Comfort Book ไป อ่านสลับกับมองคนเดินผ่านแล้วรู้สึกว่าใจกลับมาอยู่กับตัวเอง",userEmail:"June · Cup of Calm",createdAt:"เมื่อ 34 นาทีที่แล้ว"},
  {id:-3,kind:"podcast",title:"พอดแคสต์ตอนนี้ทำให้คำว่า “พัก” ไม่รู้สึกผิด",body:"ฟังระหว่างเดินกลับบ้าน ความยาวยี่สิบนาทีพอดี ประโยคที่เก็บกลับมาคือ เราไม่จำเป็นต้องทำทุกช่วงเวลาให้เกิดประโยชน์",userEmail:"Tin · Cup of Enough",createdAt:"เมื่อ 1 ชั่วโมงที่แล้ว"},
];

export default function ClubPage(){
  const [posts,setPosts]=useState<Post[]>([]);const [title,setTitle]=useState("");const [body,setBody]=useState("");const [kind,setKind]=useState("book");const [filter,setFilter]=useState("all");const [expanded,setExpanded]=useState(false);const [liked,setLiked]=useState<Set<number>>(new Set());const [saved,setSaved]=useState<Set<number>>(new Set());
  const load=()=>fetch("/api/community").then(r=>r.json()).then(d=>setPosts(d.posts??[])).catch(()=>setPosts([]));
  useEffect(()=>{load()},[]);
  const publish=async()=>{let guestId=localStorage.getItem("cup-of-us-guest");if(!guestId){guestId=`guest-${crypto.randomUUID()}`;localStorage.setItem("cup-of-us-guest",guestId)}const response=await fetch("/api/community",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({guestId,kind,title,body})});if(response.ok){setTitle("");setBody("");setExpanded(false);load()}};
  const feed=useMemo(()=>{const source=posts.length?posts:samples;return filter==="all"?source:source.filter(post=>post.kind===filter)},[posts,filter]);
  const toggle=(setter:React.Dispatch<React.SetStateAction<Set<number>>>,id:number)=>setter(current=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next});
  return <main className="club-page"><nav className="catalog-nav"><a className="logo" href="/"><span>CUP</span><i>of</i><span>US</span></a><div><a href="/discover">Cup Directory</a><a href="/brew">ชงแก้วของฉัน</a><a className="profile-icon" href="/profile" aria-label="โปรไฟล์">●</a></div></nav>
    <header className="club-feed-hero"><div><p className="eyebrow">CUP (CLUB) · SOCIAL NOTES</p><h1>พื้นที่เล็ก ๆ<br/><em>สำหรับสิ่งที่อยากเล่าต่อ</em></h1><p>ฟีดป้ายยาหนังสือ เพลง หนัง พอดแคสต์ และคาเฟ่ จากคนที่กำลังพยายามดูแลชีวิตในแบบของตัวเอง</p></div><a href="#compose"><span>＋</span><b>เขียนโพสต์แรกของคุณ<small>ไม่ต้องเขียนให้เก่ง แค่เล่าให้จริง</small></b></a></header>
    <div className="club-shell"><aside className="club-rail"><p className="eyebrow">เลือกอ่านตามรส</p><nav>{kinds.map(item=><button className={filter===item.id?"active":""} onClick={()=>setFilter(item.id)} type="button" key={item.id}><i>{item.icon}</i>{item.label}</button>)}</nav><div><b>Cup Club Rules</b><small>เล่าประสบการณ์จริง<br/>ให้เครดิตเจ้าของผลงาน<br/>เห็นต่างได้ แต่อ่อนโยนต่อกัน</small></div></aside>
      <section className="club-stream"><form id="compose" className={`club-inline-compose${expanded?" is-expanded":""}`} onSubmit={event=>{event.preventDefault();publish()}}><div className="club-avatar">CU</div><div><label htmlFor="club-title">วันนี้มีอะไรที่อยากป้ายยา?</label><input id="club-title" value={title} onFocus={()=>setExpanded(true)} onChange={event=>setTitle(event.target.value)} required placeholder="ชื่อหนังสือ เพลง หนัง พอดแคสต์ หรือคาเฟ่"/>{expanded&&<><textarea value={body} onChange={event=>setBody(event.target.value)} required placeholder="มันอยู่กับคุณในวันแบบไหน? มีประโยคหรือความรู้สึกอะไรที่อยากส่งต่อ?"/><footer><div>{kinds.slice(1).map(item=><button className={kind===item.id?"active":""} onClick={()=>setKind(item.id)} type="button" key={item.id}><i>{item.icon}</i><span>{item.label}</span></button>)}</div><button className="club-publish" type="submit">แปะโพสต์นี้ →</button></footer></>}</div></form>
        <div className="club-stream-head"><div><p className="eyebrow">FRESHLY BREWED</p><h2>{kinds.find(item=>item.id===filter)?.label??"ทั้งหมด"}</h2></div><span>{feed.length} โพสต์</span></div>
        <div className="club-post-list">{feed.length?feed.map((post,index)=>{const meta=kinds.find(item=>item.id===post.kind)??kinds[1];return <article className={`club-post note-${index%3}`} key={post.id}><div className="club-post-avatar">{meta.icon}</div><div className="club-post-content"><header><div><b>{post.userEmail?.split("@")[0]??"สมาชิก Cup of Us"}</b><span>· {post.createdAt&&post.createdAt.includes("T")?"โพสต์ล่าสุด":post.createdAt??"เพิ่งแปะ"}</span></div><small>{meta.icon} {meta.label}</small></header><h3>{post.title}</h3><p>{post.body}</p><footer><button className={liked.has(post.id)?"active":""} onClick={()=>toggle(setLiked,post.id)} type="button" aria-label="ถูกใจโพสต์"><i>♡</i><span>{liked.has(post.id)?"ถูกใจแล้ว":"ถูกใจ"}</span></button><button type="button"><i>↳</i><span>ตอบกลับ</span></button><button type="button"><i>↗</i><span>ส่งต่อ</span></button><button className={saved.has(post.id)?"active save":"save"} onClick={()=>toggle(setSaved,post.id)} type="button"><i>▣</i><span>{saved.has(post.id)?"เก็บแล้ว":"เก็บโพสต์"}</span></button></footer></div></article>}):<div className="club-empty"><span>☕</span><h3>มุมนี้ยังว่างอยู่</h3><p>ลองแปะโพสต์แรกของรสนี้ให้คนถัดไปได้เจอ</p><button onClick={()=>document.getElementById("club-title")?.focus()} type="button">เริ่มเขียนโพสต์ →</button></div>}</div>
      </section><aside className="club-now"><p className="eyebrow">กำลังคุยกัน</p><article><b>#เริ่มใหม่ทีละนิด</b><span>12 แก้วกำลังแลกเปลี่ยน</span></article><article><b>#หนังสือในวันใจล้า</b><span>8 แก้วกำลังแลกเปลี่ยน</span></article><article><b>#คาเฟ่นั่งอ่านได้นาน</b><span>6 แก้วกำลังแลกเปลี่ยน</span></article><a href="/brew">ยังไม่มีแก้วของตัวเอง?<br/><b>ลองชงใน 2 นาที →</b></a></aside></div>
  </main>;
}
