"use client";
import { useEffect, useState } from "react";
import "./profile.css";import "./onboarding.css";
type Cup={id:number;cupName:string;bookSlug:string;bookTitle:string;coverColor:string;answers:string};
export default function ProfilePage(){const [name,setName]=useState("");const [draft,setDraft]=useState("");const [guestId,setGuestId]=useState("");const [cups,setCups]=useState<Cup[]>([]);const [loading,setLoading]=useState(true);
  const load=async(id:string)=>{const [profile,cupData]=await Promise.all([fetch(`/api/profile?guestId=${encodeURIComponent(id)}`).then(r=>r.json()),fetch(`/api/saved-cups?guestId=${encodeURIComponent(id)}`).then(r=>r.json())]);setName(profile.profile?.displayName??"");setDraft(profile.profile?.displayName??"");setCups(cupData.cups??[]);setLoading(false)};
  useEffect(()=>{let id=localStorage.getItem("cup-of-us-guest");if(!id){id=`guest-${crypto.randomUUID()}`;localStorage.setItem("cup-of-us-guest",id)}setGuestId(id);load(id)},[]);
  const save=async()=>{const value=draft.trim();if(!value)return;const response=await fetch("/api/profile",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({guestId,displayName:value})});if(response.ok){setName(value);localStorage.setItem("cup-of-us-name",value)}};
  return <main className="profile-page"><a className="logo" href="/"><span>CUP</span><i>of</i><span>US</span></a><section>{loading?<p>กำลังหยิบแก้วของคุณ...</p>:name?<><p className="eyebrow">MY CUP PROFILE · SAVED IN CUP OF US</p><h1>สวัสดี {name} ☺</h1><p>คุณทดลองชงได้โดยไม่ล็อกอิน แก้วที่กดเก็บจะบันทึกไว้ในฐาน Cup of Us ด้วยรหัส Guest ของอุปกรณ์นี้</p><div className="profile-stats"><div><b>{cups.length}</b><span>แก้วที่เก็บไว้</span></div><div><b>7</b><span>ส่วนผสมต่อแก้ว</span></div><div><b>50</b><span>หนังสือในตู้</span></div></div><h2>แก้วของฉัน</h2>{cups.length?<div className="saved-cup-list">{cups.map(cup=><a href={`/cup/${cup.bookSlug}`} key={cup.id} style={{"--saved-color":cup.coverColor} as React.CSSProperties}><i></i><div><b>{cup.cupName}</b><span>{cup.bookTitle}</span></div><strong>→</strong></a>)}</div>:<p className="empty-profile">ยังไม่มีแก้วที่เก็บไว้ — ลองชงหรือเปิดหนังสือแล้วกด “เก็บแก้วนี้”</p>}<div className="profile-actions"><a href="/brew">ชงแก้วใหม่</a><a href="/discover">ค้นหนังสือ</a></div></>:<><p className="eyebrow">KEEP YOUR CUPS</p><h1>เรียกคุณว่าอะไรดี?</h1><p>ตั้งชื่อสั้น ๆ ตอนที่อยากเก็บแก้ว ไม่ต้องใช้อีเมล รหัสผ่าน หรือ ChatGPT OAuth</p><div className="local-signup"><input value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>e.key==="Enter"&&save()} placeholder="ชื่อหรือ nickname" aria-label="ชื่อโปรไฟล์"/><button onClick={save} type="button">เริ่มเก็บแก้ว →</button></div><small>หากต้องการซิงก์ข้ามอุปกรณ์ เราจะเพิ่มการยืนยันบัญชีในเฟสแอปภายหลัง</small></>}</section></main>}
