import { integer, pgTable, serial, text, timestamp, uniqueIndex } from "drizzle-orm/pg-core";

const createdAt = () => timestamp("created_at", { withTimezone: true }).notNull().defaultNow();

export const books = pgTable("books", {
  id: serial("id").primaryKey(), slug: text("slug").notNull().unique(), title: text("title").notNull(), thaiTitle: text("thai_title"), author: text("author").notNull(), coverColor: text("cover_color").notNull(), coverTextColor: text("cover_text_color").notNull().default("#172f2b"), summary: text("summary").notNull(), tags: text("tags").notNull(), concerns: text("concerns").notNull(), personality: text("personality").notNull(), readingMinutes: integer("reading_minutes").notNull().default(300), audioUrl: text("audio_url"), podcastUrl: text("podcast_url"), kinokuniyaUrl: text("kinokuniya_url"), shopeeUrl: text("shopee_url"), lazadaUrl: text("lazada_url"), naiinUrl: text("naiin_url"), thaimartUrl: text("thaimart_url"),
});
export const profiles = pgTable("profiles", { id: serial("id").primaryKey(), email: text("email").notNull().unique(), displayName: text("display_name").notNull(), bio: text("bio").notNull().default(""), favoriteTopics: text("favorite_topics").notNull().default("[]"), createdAt: createdAt() });
export const savedCups = pgTable("saved_cups", { id: serial("id").primaryKey(), userEmail: text("user_email").notNull(), bookId: integer("book_id").notNull().references(() => books.id), cupName: text("cup_name").notNull(), answers: text("answers").notNull(), createdAt: createdAt() });
export const creatorPosts = pgTable("creator_posts", { id: serial("id").primaryKey(), userEmail: text("user_email").notNull(), kind: text("kind").notNull(), title: text("title").notNull(), body: text("body").notNull(), bookId: integer("book_id").references(() => books.id), status: text("status").notNull().default("draft"), createdAt: createdAt() });
export const mediaPairings = pgTable("media_pairings", { id: serial("id").primaryKey(), bookSlug: text("book_slug").notNull().unique(), songTitle: text("song_title").notNull(), songArtist: text("song_artist").notNull(), songUrl: text("song_url"), movieTitle: text("movie_title").notNull(), movieYear: integer("movie_year"), movieUrl: text("movie_url"), mood: text("mood").notNull(), reason: text("reason").notNull() });
export const coffeePairings = pgTable("coffee_pairings", { id: serial("id").primaryKey(), bookSlug: text("book_slug").notNull().unique(), menuName: text("menu_name").notNull(), menuNameThai: text("menu_name_thai").notNull(), ingredients: text("ingredients").notNull(), brewMethod: text("brew_method").notNull(), orderTip: text("order_tip").notNull(), caffeine: text("caffeine").notNull(), layerTop: text("layer_top").notNull(), layerBottom: text("layer_bottom").notNull() });
export const analyticsEvents = pgTable("analytics_events", { id: serial("id").primaryKey(), sessionId: text("session_id").notNull(), eventName: text("event_name").notNull(), bookSlug: text("book_slug"), source: text("source"), metadata: text("metadata").notNull().default("{}"), createdAt: createdAt() });
export const authUsers = pgTable("auth_users", { id: serial("id").primaryKey(), email: text("email").notNull().unique(), displayName: text("display_name").notNull(), passwordHash: text("password_hash").notNull(), passwordSalt: text("password_salt").notNull(), emailVerifiedAt: timestamp("email_verified_at", { withTimezone: true }), createdAt: createdAt() });
export const authSessions = pgTable("auth_sessions", { id: serial("id").primaryKey(), userId: integer("user_id").notNull().references(() => authUsers.id, { onDelete: "cascade" }), tokenHash: text("token_hash").notNull().unique(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), createdAt: createdAt() });
export const authTokens = pgTable("auth_tokens", { id: serial("id").primaryKey(), userId: integer("user_id").notNull().references(() => authUsers.id, { onDelete: "cascade" }), purpose: text("purpose").notNull(), tokenHash: text("token_hash").notNull().unique(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), usedAt: timestamp("used_at", { withTimezone: true }), createdAt: createdAt() });
export const authRateLimits = pgTable("auth_rate_limits", { id: serial("id").primaryKey(), keyHash: text("key_hash").notNull().unique(), attempts: integer("attempts").notNull().default(0), resetAt: timestamp("reset_at", { withTimezone: true }).notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() });
export const authIdentities = pgTable("auth_identities", { id: serial("id").primaryKey(), userId: integer("user_id").notNull().references(() => authUsers.id, { onDelete: "cascade" }), provider: text("provider").notNull(), providerSubject: text("provider_subject").notNull(), createdAt: createdAt() }, (table) => [uniqueIndex("auth_identity_provider_subject_unique").on(table.provider, table.providerSubject)]);
