"use client";
import { useEffect, useRef, useState } from "react";
import { useParams } from "next/navigation";
import { AudioSummaryPlayer } from "../../components/AudioSummaryPlayer";
import { BookEntrance } from "../../components/BookEntrance";

type Book={id:number;slug:string;title:string;thaiTitle?:string;author:string;coverColor:string;summary:string;tags:string;readingMinutes:number;kinokuniyaUrl?:string;shopeeUrl?:string;lazadaUrl?:string;naiinUrl?:string};
type Pairing={songTitle:string;songArtist:string;songUrl?:string;movieTitle:string;movieYear?:number;movieUrl?:string;mood:string;reason:string};
type SpotifyTrack={embedUrl:string;name:string;artists:{name:string}[]};
type CoffeePairing={menuName:string;menuNameThai:string;ingredients:string;brewMethod:string;orderTip:string;caffeine:string;layerTop:string;layerBottom:string};

const featuredMedia:Record<string,{youtubeId:string;youtubeTitle:string;spotifyId:string}>={
  "atomic-habits":{youtubeId:"PZ7lDrwYdZc",youtubeTitle:"How to become 37.78 times better at anything",spotifyId:"3obMEhRz8BsE5oQgqykAZm"},
  "courage-to-be-disliked":{youtubeId:"koYFXh3WEao",youtubeTitle:"The Courage To Be Disliked — Animated Summary",spotifyId:"2OlRMsKSn8aZQw1rR1Mo5W"},
  "maybe-you-should-talk":{youtubeId:"5OwF5b0X2SI",youtubeTitle:"Maybe You Should Talk to Someone — 3 Minute Summary",spotifyId:"3CzmuYbC5N9gmocO99Z5KT"},
  "deep-work":{youtubeId:"ZD7dXfdDPfg",youtubeTitle:"Deep Work by Cal Newport — Animated Summary",spotifyId:"5VfEuwErhx6X4eaPbyBfyu"},
  "four-thousand-weeks":{youtubeId:"nnMlyA0kcB8",youtubeTitle:"Four Thousand Weeks — Book Summary",spotifyId:"561F1zqRwGPCTMRsLsXVtL"},
  "designing-your-life":{youtubeId:"ZuyGMVYzQyI",youtubeTitle:"Designing Your Life — Core Message",spotifyId:"3U5JVgI2x4rDyHGObzJfNf"},
  "the-comfort-book":{youtubeId:"Yc_lmBnehpc",youtubeTitle:"The Comfort Book by Matt Haig — 9 Minute Summary",spotifyId:"6dGnYIeXmHdcikdzNNDMm2"},
  "essentialism":{youtubeId:"eDBYci4Vy2k",youtubeTitle:"Essentialism by Greg McKeown — Visual Summary",spotifyId:"6K4t31amVTZDgR3sKmwUJJ"},
};

export default function CupDetail(){const params=useParams<{slug:string}>();const slug=params.slug;const featured=featuredMedia[slug];const [book,setBook]=useState<Book|null>(null);const [pair,setPair]=useState<Pairing|null>(null);const [coffee,setCoffee]=useState<CoffeePairing|null>(null);const [spotify,setSpotify]=useState<SpotifyTrack|null>(null);const [sound,setSound]=useState(false);const [saved,setSaved]=useState(false);const audio=useRef<AudioContext|null>(null);
  const guest=()=>{let id=localStorage.getItem("cup-of-us-guest");if(!id){id=`guest-${crypto.randomUUID()}`;localStorage.setItem("cup-of-us-guest",id)}return id};
  const track=(eventName:string,source?:string)=>fetch("/api/events",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({sessionId:guest(),eventName,bookSlug:slug,source})}).catch(()=>{});
  useEffect(()=>{Promise.all([fetch(`/api/books?slug=${slug}`).then(r=>r.json()),fetch(`/api/external/media?slug=${slug}`).then(r=>r.json()),fetch(`/api/coffee?slug=${slug}`).then(r=>r.json())]).then(([b,p,c])=>{setBook(b.book);setPair(p.pairing);setSpotify(p.spotify??null);setCoffee(c.pairing??null);track("view_cup")})},[slug]);
  const toggleSound=()=>{if(audio.current){audio.current.close();audio.current=null;setSound(false);return}const Ctx=window.AudioContext||(window as unknown as {webkitAudioContext:typeof AudioContext}).webkitAudioContext;const ctx=new Ctx();const gain=ctx.createGain();gain.gain.value=.035;gain.connect(ctx.destination);[164.81,220,277.18].forEach((frequency,index)=>{const osc=ctx.createOscillator();const tone=ctx.createGain();osc.type=index===0?"sine":"triangle";osc.frequency.value=frequency;tone.gain.value=index===0?.7:.22;osc.connect(tone);tone.connect(gain);osc.start()});audio.current=ctx;setSound(true)};
  const saveCup=async()=>{if(!book)return;const answers=JSON.parse(localStorage.getItem("cup-of-us-last-answers")??"[]");const response=await fetch("/api/saved-cups",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({guestId:guest(),bookId:book.id,cupName:`Cup of ${book.title}`,answers})});if(response.ok){setSaved(true);track("save_cup")}};
  if(!book)return <main className="cup-loading">กำลังชงรายละเอียดแก้วนี้...</main>;
  return <main className="cup-detail"><BookEntrance title={book.title} author={book.author} color={book.coverColor}/><nav className="catalog-nav"><a className="logo" href="/"><span>CUP</span><i>of</i><span>US</span></a><div><a href="/discover">← Cup Directory</a><a className="profile-icon" href="/profile" aria-label="โปรไฟล์">●</a></div></nav>
    <header className="cup-detail-hero"><div className="cup-detail-hero-inner"><div className="detail-cover" style={{"--cover":book.coverColor} as React.CSSProperties}><small>{book.author}</small><b>{book.title}</b><i>BREWED FOR YOU</i></div><div className="cup-detail-copy"><p className="eyebrow">ONE CUP · FOUR WAYS TO STAY</p><h1>{book.title}</h1><h2>{book.thaiTitle}</h2><p>{book.summary}</p><div className="detail-tags">{book.tags.split(",").map(x=><span key={x}>{x}</span>)}</div><div className="detail-jump"><a href="#read">อ่าน</a><a href="#listen">ฟัง</a><a href="#watch">ดู</a><a href="#buy">ซื้อ</a><button onClick={saveCup} type="button">{saved?"เก็บแก้วแล้ว ✓":"เก็บแก้วนี้ ♡"}</button></div></div></div></header>
    {coffee&&<section className="coffee-menu-section" style={{"--coffee-top":coffee.layerTop,"--coffee-bottom":coffee.layerBottom} as React.CSSProperties}><div className="coffee-menu-cup"><div className="coffee-liquid-art"></div><b>cup<br/><i>of</i><br/>us</b></div><div className="coffee-menu-copy"><p className="eyebrow">YOUR BOOK · YOUR REAL DRINK</p><h2>{coffee.menuNameThai}<small>{coffee.menuName}</small></h2><p>เมนูประจำหนังสือเล่มนี้ ชงเองได้และใช้ประโยคด้านล่างสั่งกับคาเฟ่ในไทยได้ทันที</p><div className="coffee-recipe-grid"><div><span>ส่วนผสม</span><b>{coffee.ingredients.replaceAll(","," · ")}</b></div><div><span>ชงแบบนี้</span><b>{coffee.brewMethod}</b></div><div><span>สั่งที่คาเฟ่</span><b>“{coffee.orderTip}”</b></div><div><span>คาเฟอีน</span><b>{coffee.caffeine}</b></div></div></div></section>}
    <section className="experience-grid">
      <article id="read" className="experience read-panel"><p className="eyebrow">01 · READ THE CUP</p><h2>สรุปแก่นสำคัญ<br/>ใน 5–8 นาที</h2><p>{book.summary} เราชวนคุณเริ่มจากการสังเกตสิ่งเล็กที่สุดที่ทำได้ในวันนี้ แล้วออกแบบสภาพแวดล้อมให้การกลับมาทำซ้ำง่ายขึ้น</p><blockquote>ไม่ต้องเปลี่ยนทั้งชีวิตในครั้งเดียว แค่เลือกหนึ่งคะแนนให้ตัวเองคนใหม่</blockquote><a href={`/read/${slug}`}>อ่านฉบับเต็มของเล่มนี้ →</a></article>
      <article id="listen" className="experience listen-panel"><div className="experience-inner"><p className="eyebrow">02 · ฟังและดูสรุป</p><h2>ฟังหนังสือ<br/>ในแก้วนี้</h2>{featured&&<div className="youtube-summary"><iframe src={`https://www.youtube-nocookie.com/embed/${featured.youtubeId}?playsinline=1&rel=0`} title={`${book.title} — YouTube book summary`} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen loading="lazy"></iframe><div><span>YOUTUBE BOOK SUMMARY</span><b>{featured.youtubeTitle}</b><small>คลิปสรุปที่พูดถึงหนังสือเล่มนี้โดยตรง</small></div></div>}<AudioSummaryPlayer title={book.title} text={`${book.summary}. ${pair?.reason??""}`}/>{(spotify||featured)&&<iframe className="spotify-player" src={spotify?.embedUrl??`https://open.spotify.com/embed/track/${featured?.spotifyId}?utm_source=generator`} width="100%" height="152" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy" title={`${pair?.songTitle??book.title} on Spotify`}></iframe>}<h3>{pair?.songTitle??"A Gentle Cup"}</h3><p>{pair?.songArtist??"Cup of Us Studio"} · เพลงที่จับคู่กับหนังสือเล่มนี้</p><div className="media-buttons"><button onClick={toggleSound}>{sound?"Ⅱ พักเสียงบรรยากาศ":"▶ เล่นเสียงบรรยากาศกาแฟ"}</button></div>{pair?.songUrl&&<a href={pair.songUrl} target="_blank" rel="noreferrer">เปิดเพลงบน Spotify ↗</a>}</div></article>
      <article id="watch" className="experience watch-panel"><div className="experience-inner"><p className="eyebrow">03 · A FILM FOR THIS CUP</p><div className="movie-pairing-card"><span>MOVIE PAIRING · {pair?.movieYear??"CUP OF US"}</span><strong>{pair?.movieTitle??"One Small Step"}</strong><i>{pair?.mood??"a film for this cup"}</i></div><p className="movie-kicker">ถ้าชอบแก้วนี้ ลองดูเรื่องนี้ต่อ</p><h2>{pair?.movieTitle??"One Small Step"} <small>{pair?.movieYear}</small></h2><p>{pair?.reason??"เรื่องเล่าที่ทำให้แนวคิดของหนังสือมองเห็นได้ชัดขึ้น"}</p>{pair?.movieUrl&&<a className="movie-link" href={pair.movieUrl} target="_blank" rel="noreferrer">ดูตัวอย่างและช่องทางรับชม ↗</a>}</div></article>
      <article id="buy" className="experience buy-panel"><p className="eyebrow">04 · FIND THE BOOK</p><h2>เลือกซื้อจาก<br/>ร้านที่คุณไว้ใจ</h2><p>ทุกลิงก์ค้นหาด้วยชื่อหนังสือและผู้เขียนของเล่มนี้โดยเฉพาะ เราไม่ขายหนังสือโดยตรง และลิงก์บางรายการอาจสร้างค่าคอมมิชชันโดยไม่เพิ่มราคาของคุณ</p><div className="detail-stores">{(()=>{const q=encodeURIComponent(`${book.title} ${book.author}`);const links=[["Kinokuniya",book.kinokuniyaUrl||`https://thailand.kinokuniya.com/products?keywords=${q}`],["Shopee",book.shopeeUrl||`https://shopee.co.th/search?keyword=${q}`],["Lazada",book.lazadaUrl||`https://www.lazada.co.th/catalog/?q=${q}`],["Naiin",book.slug==="atomic-habits"?"https://www.naiin.com/product/detail/508699":book.naiinUrl||`https://www.naiin.com/search-result?keyword=${q}`]];return links.map(([name,url])=><a href={url} onClick={()=>track("retailer_click",name)} target="_blank" rel="noreferrer sponsored" key={name}><b>{name}</b><span>ค้นหา {book.title}</span><i>↗</i></a>)})()}</div></article>
    </section>
  </main>}
