"use client";
import { useEffect, useRef, useState } from "react";
import { useParams } from "next/navigation";

type Book={id:number;slug:string;title:string;thaiTitle?:string;author:string;coverColor:string;summary:string;tags:string;readingMinutes:number;kinokuniyaUrl?:string;shopeeUrl?:string;lazadaUrl?:string;naiinUrl?:string};
type Pairing={songTitle:string;songArtist:string;songUrl?:string;movieTitle:string;movieYear?:number;movieUrl?:string;mood:string;reason:string};
type SpotifyTrack={embedUrl:string;name:string;artists:{name:string}[]};

export default function CupDetail(){const params=useParams<{slug:string}>();const slug=params.slug;const [book,setBook]=useState<Book|null>(null);const [pair,setPair]=useState<Pairing|null>(null);const [spotify,setSpotify]=useState<SpotifyTrack|null>(null);const [sound,setSound]=useState(false);const [film,setFilm]=useState(false);const [saved,setSaved]=useState(false);const audio=useRef<AudioContext|null>(null);
  const guest=()=>{let id=localStorage.getItem("cup-of-us-guest");if(!id){id=`guest-${crypto.randomUUID()}`;localStorage.setItem("cup-of-us-guest",id)}return id};
  const track=(eventName:string,source?:string)=>fetch("/api/events",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({sessionId:guest(),eventName,bookSlug:slug,source})}).catch(()=>{});
  useEffect(()=>{Promise.all([fetch(`/api/books?slug=${slug}`).then(r=>r.json()),fetch(`/api/external/media?slug=${slug}`).then(r=>r.json())]).then(([b,p])=>{setBook(b.book);setPair(p.pairing);setSpotify(p.spotify??null);track("view_cup")})},[slug]);
  const toggleSound=()=>{if(audio.current){audio.current.close();audio.current=null;setSound(false);return}const Ctx=window.AudioContext||(window as unknown as {webkitAudioContext:typeof AudioContext}).webkitAudioContext;const ctx=new Ctx();const gain=ctx.createGain();gain.gain.value=.035;gain.connect(ctx.destination);[164.81,220,277.18].forEach((frequency,index)=>{const osc=ctx.createOscillator();const tone=ctx.createGain();osc.type=index===0?"sine":"triangle";osc.frequency.value=frequency;tone.gain.value=index===0?.7:.22;osc.connect(tone);tone.connect(gain);osc.start()});audio.current=ctx;setSound(true)};
  const speak=()=>{speechSynthesis.cancel();const utter=new SpeechSynthesisUtterance(`${book?.title}. ${book?.summary}. ${pair?.reason??""}`);utter.lang="th-TH";utter.rate=.88;speechSynthesis.speak(utter)};
  const saveCup=async()=>{if(!book)return;const answers=JSON.parse(localStorage.getItem("cup-of-us-last-answers")??"[]");const response=await fetch("/api/saved-cups",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({guestId:guest(),bookId:book.id,cupName:`Cup of ${book.title}`,answers})});if(response.ok){setSaved(true);track("save_cup")}};
  if(!book)return <main className="cup-loading">กำลังชงรายละเอียดแก้วนี้...</main>;
  return <main className="cup-detail"><nav className="catalog-nav"><a className="logo" href="/"><span>CUP</span><i>of</i><span>US</span></a><div><a href="/discover">← Cup Directory</a><a className="profile-icon" href="/profile" aria-label="โปรไฟล์">●</a></div></nav>
    <header className="cup-detail-hero"><div className="detail-cover" style={{"--cover":book.coverColor} as React.CSSProperties}><small>{book.author}</small><b>{book.title}</b><i>BREWED FOR YOU</i></div><div><p className="eyebrow">ONE CUP · FOUR WAYS TO STAY</p><h1>{book.title}</h1><h2>{book.thaiTitle}</h2><p>{book.summary}</p><div className="detail-tags">{book.tags.split(",").map(x=><span key={x}>{x}</span>)}</div><div className="detail-jump"><a href="#read">อ่าน</a><a href="#listen">ฟัง</a><a href="#watch">ดู</a><a href="#buy">ซื้อ</a><button onClick={saveCup} type="button">{saved?"เก็บแก้วแล้ว ✓":"เก็บแก้วนี้ ♡"}</button></div></div></header>
    <section className="experience-grid">
      <article id="read" className="experience read-panel"><p className="eyebrow">01 · READ THE CUP</p><h2>สรุปแก่นสำคัญ<br/>ใน 5–8 นาที</h2><p>{book.summary} เราชวนคุณเริ่มจากการสังเกตสิ่งเล็กที่สุดที่ทำได้ในวันนี้ แล้วออกแบบสภาพแวดล้อมให้การกลับมาทำซ้ำง่ายขึ้น</p><blockquote>ไม่ต้องเปลี่ยนทั้งชีวิตในครั้งเดียว แค่เลือกหนึ่งคะแนนให้ตัวเองคนใหม่</blockquote><a href={`/read/${slug}`}>อ่านฉบับเต็มของเล่มนี้ →</a></article>
      <article id="listen" className="experience listen-panel"><p className="eyebrow">02 · LISTEN IN HERE</p><h2>Cup of Us<br/>Listen Bar</h2>{spotify?<iframe className="spotify-player" src={spotify.embedUrl} width="100%" height="152" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy" title={`${spotify.name} on Spotify`}></iframe>:<div className={`sound-orbit ${sound?"playing":""}`}><i></i><i></i><i></i><b>♪</b></div>}<h3>{pair?.songTitle??"A Gentle Cup"}</h3><p>{pair?.songArtist??"Cup of Us Studio"} · เพลงที่จับคู่กับหนังสือเล่มนี้</p><div className="media-buttons"><button onClick={toggleSound}>{sound?"■ หยุด Original Sound":"▶ เล่น Original Sound"}</button><button onClick={speak}>◉ ฟัง Audio Summary</button></div>{pair?.songUrl&&<a href={pair.songUrl} target="_blank" rel="noreferrer">เปิดเพลงชื่อเดียวกันบน Spotify ↗</a>}</article>
      <article id="watch" className="experience watch-panel"><p className="eyebrow">03 · WATCH THE IDEA</p><div className={`micro-film ${film?"playing":""}`}><div className="film-sun"></div><div className="film-person"></div><p>{film?"ONE SMALL STEP":"CUP OF US MICRO FILM"}</p></div><h2>{pair?.movieTitle??"One Small Step"} <small>{pair?.movieYear}</small></h2><p>{pair?.reason??"เรื่องเล่าสั้นที่ทำให้แนวคิดของหนังสือมองเห็นได้"}</p><button onClick={()=>setFilm(!film)}>{film?"ดูอีกครั้ง ↻":"▶ ดู Micro Film 20 วินาที"}</button>{pair?.movieUrl&&<a href={pair.movieUrl} target="_blank" rel="noreferrer">ดูข้อมูลหนังที่เข้าคู่กัน ↗</a>}</article>
      <article id="buy" className="experience buy-panel"><p className="eyebrow">04 · FIND THE BOOK</p><h2>เลือกซื้อจาก<br/>ร้านที่คุณไว้ใจ</h2><p>ทุกลิงก์ค้นหาด้วยชื่อหนังสือและผู้เขียนของเล่มนี้โดยเฉพาะ เราไม่ขายหนังสือโดยตรง และลิงก์บางรายการอาจสร้างค่าคอมมิชชันโดยไม่เพิ่มราคาของคุณ</p><div className="detail-stores">{(()=>{const q=encodeURIComponent(`${book.title} ${book.author}`);const links=[["Kinokuniya",book.kinokuniyaUrl||`https://thailand.kinokuniya.com/products?keywords=${q}`],["Shopee",book.shopeeUrl||`https://shopee.co.th/search?keyword=${q}`],["Lazada",book.lazadaUrl||`https://www.lazada.co.th/catalog/?q=${q}`],["Naiin",book.slug==="atomic-habits"?"https://www.naiin.com/product/detail/508699":book.naiinUrl||`https://www.naiin.com/search-result?keyword=${q}`]];return links.map(([name,url])=><a href={url} onClick={()=>track("retailer_click",name)} target="_blank" rel="noreferrer sponsored" key={name}><b>{name}</b><span>ค้นหา {book.title}</span><i>↗</i></a>)})()}</div></article>
    </section>
  </main>}
